AppBundle\Entity\Ticket:
    type: entity
    table: tickets
    repositoryClass: AppBundle\Entity\TicketRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        content:
            type: text
        status:
            type: integer
        createdTime:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedTime:
            type: datetime
            gedmo:
                timestampable:
                    on: update