<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * LastCollectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastCollectRepository extends \Doctrine\ORM\EntityRepository
{
}
