<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * MailinglistThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailinglistThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
