<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * MailinglistListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailinglistListRepository extends \Doctrine\ORM\EntityRepository
{
}
