<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * MailinglistPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailinglistPostRepository extends \Doctrine\ORM\EntityRepository
{
}
