<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * WikitalkThreadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WikitalkThreadRepository extends \Doctrine\ORM\EntityRepository
{
}
