<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * WikipageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WikipageRepository extends \Doctrine\ORM\EntityRepository
{
}
