<?php

namespace OSM\ComCollectBundle\Repository;

/**
 * WikitalkPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WikitalkPostRepository extends \Doctrine\ORM\EntityRepository
{
}
